REDIS_HOST = 'local_host'
REDIS_PORT = 7777
# REDIS_PASSWORD = 'very secret'

# Queues to listen on
QUEUES = ['get','crawl', 'other']

# If you want to use a dictConfig <https://docs.python.org/3/library/logging.config.html#logging-config-dictschema>
# for more complex/consistent logging requirements.
DICT_CONFIG = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
        },
    },
    'handlers': {
        'default': {
            'level': 'INFO',
            'formatter': 'standard',
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stderr',  # Default is stderr
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler'
            'formatter': 'precise',
            'filename': 'redis.log',
            'maxBytes': 1024,
            'backupCount': 2
        }
    }
    'loggers': {
        'root': {  # root logger
            'handlers': ['default'],
            'level': 'INFO',
            'propagate': False
        },
    }
}
